# Generated by Django 4.2.13 on 2024-07-04 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lift",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Lift", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Movement", max_length=200)),
                (
                    "lift",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="tracker.lift",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Piece", max_length=200)),
                (
                    "duration",
                    models.DurationField(default=datetime.timedelta(seconds=1)),
                ),
                ("distance", models.FloatField(default=1)),
                ("units", models.CharField(default="miles", max_length=200)),
                ("calories", models.IntegerField(default=1)),
                ("notes", models.TextField(default="")),
                ("is_distance_piece", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Plan", max_length=200)),
                ("description", models.TextField(default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingZone",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Zone 0", max_length=200)),
                ("description", models.TextField(default="", max_length=200)),
                ("min_hr", models.IntegerField(default=1)),
                ("max_hr", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(default="User", max_length=200)),
                ("email", models.EmailField(default="", max_length=200)),
                (
                    "default_plan",
                    models.OneToOneField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_user",
                        to="tracker.plan",
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(related_name="following", to="tracker.user"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "duration",
                    models.DurationField(default=datetime.timedelta(seconds=1)),
                ),
                ("distance", models.FloatField(default=1)),
                ("units", models.CharField(default="miles", max_length=200)),
                ("calories", models.IntegerField(default=1)),
                ("notes", models.TextField(default="")),
                ("is_completed", models.BooleanField(default=False)),
                ("workout_type", models.CharField(default="Other", max_length=200)),
                ("is_indoor", models.BooleanField(default=False)),
                (
                    "cooldown",
                    models.OneToOneField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooldown",
                        to="tracker.piece",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="tracker.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="tracker.user",
                    ),
                ),
                (
                    "warmup",
                    models.OneToOneField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warmup",
                        to="tracker.piece",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("num_reps", models.IntegerField(default=1)),
                ("weight", models.FloatField(default=1)),
                ("units", models.CharField(default="pounds", max_length=200)),
                (
                    "lift",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="tracker.movement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plan",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="tracker.user",
            ),
        ),
        migrations.AddField(
            model_name="piece",
            name="training_zone",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pieces",
                to="tracker.trainingzone",
            ),
        ),
        migrations.AddField(
            model_name="piece",
            name="workout",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_pieces",
                to="tracker.workout",
            ),
        ),
        migrations.AddField(
            model_name="lift",
            name="workout",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lift",
                to="tracker.workout",
            ),
        ),
        migrations.CreateModel(
            name="FollowRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("approved", models.BooleanField(default=False)),
                (
                    "from_user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_requests_sent",
                        to="tracker.user",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_requests_received",
                        to="tracker.user",
                    ),
                ),
            ],
        ),
    ]
