# Generated by Django 4.2.13 on 2024-07-04 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_plan_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="default_plan",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_user",
                to="tracker.plan",
            ),
        ),
    ]
