# Generated by Django 4.2.13 on 2024-07-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_user_default_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to="tracker.user"
            ),
        ),
    ]
