# Generated by Django 4.2.13 on 2024-07-04 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_user_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="default_plan",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_user",
                to="tracker.plan",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="cooldown",
            field=models.OneToOneField(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cooldown",
                to="tracker.piece",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="workout",
            name="warmup",
            field=models.OneToOneField(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warmup",
                to="tracker.piece",
            ),
        ),
    ]
